// Generated by CoffeeScript 1.10.0
module.exports = function(robot) {
  robot.hear(/(whistles)/i, function(msg) {
    var response;
    response = ["its dat woo wooooo", "https://soundcloud.com/vibesquad/the-whistles", "http://i.imgur.com/KeepBS0.jpg", "http://24.media.tumblr.com/tumblr_lx31kykJQX1r2tufko1_400.jpg"];
    if (Math.random() < 0.5) {
      return msg.send(msg.random(response));
    }
  });
  robot.hear(/(tits|I approve)/i, function(msg) {
    var response;
    response = ["did someone say tits?", "TITS! ", "Woohoo!!! ... tits. ", "I may be a bot but I do love tits.", "tits! image me boobies", "woohoo! tits! animate me boobies", "Boobies!", ":tits:", ":ass:"];
    if (Math.random() < 0.9) {
      return msg.send(msg.random(response));
    }
  });
  robot.hear(/(alright)/i, function(msg) {
    var response;
    response = ["alright3x!", "alright, alright, alright!", "http://boomtownroi.com/wp-content/uploads/2015/01/All-right-all-right-all-riiiiiight-e1421264150820.jpg", "https://media.giphy.com/media/g5zvwUa9720pO/giphy.gif"];
    if (Math.random() < 0.5) {
      return msg.send(msg.random(response));
    }
  });
  return robot.hear(/(wi+oo+h)/i, function(msg) {
    var response;
    response = ["https://images.rapgenius.com/f0a9c81851ac310f1e8a745173b17126.500x373x17.gif", "WIOOOH!!!!", "https://s-media-cache-ak0.pinimg.com/736x/86/a3/c8/86a3c846b0ecdc82f1c86fb305239ead.jpg", "tits."];
    return msg.send(msg.random(response));
  });
};
