# Description:
#   Quotes by the Trailer Park Boys
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   `hey [j-roc|lahey|ricky|bubbles]` - Display a random TPB quote.
#
# Notes:
#   None
#
# Author:
#   TITLOGIC

jroc = [
  "There's 2 things mafukas gonna know about J-to-the-ROC: I spin more rhymes than a lazy Susan, and I'm innocent until mah guilt is proven! Peace! Representin' Sunnyvale, straight-the-fuck-up.",
  "(To Lahey and Randy) Why don't you run along, Gut Cassidy and the Sundance Cheeseburger. Don't look into my eyes like I got candy for you.",
  "Only wacksuckas like Cory and Trevor steal gas...and deal dope.",
  "Yo Julian, I'm going to be a daddy. Not once but two times dawg, two times.",
  "You know what I'm sayin'?",
  "Rayyyyy - Kojak's got a wig on, RAYYY!",
  "So why don't you move it along, you Rico-Suave-lookin' mafucka, cuz you ain't beatin' nobody.",
  "You mean we can't go on with the game cuz some mafucka can't go to Canadian Mafacka (Tire) and get a new orange mafucka (ball) for $2.99? That's wack, Jules.",
  "Yo, it's Rocky and Bullma'fucker.",
  "J-Roc an' da Rock-Pile ALL UP IN DIS' MA' !",
  "Naw, man, I don't play guns, mafucka.",
  "We ain't down with killin', we down with chillin'. Peace!",
  "The day J-ROC loses his flow, is the day the hair on Jim Lahey's bald head grow!",
  "(referring to Jacob) That's the fuckin' law bitch from the grocery store y'man, who you pointin' at, skeleton?",
  "This is BULL-ISH!",
  "I can't even breathe up in this piece!",
  "(to Randy) Oh what, you ain't pregnant with a bucketa chicken?",
  "(to Randy) What you talkin' 'bout, you inflatable Elvis?",
  "Oh, no, you di'n't just call me Jamie!",
  "(holding his chains to Randy's gut like a stethoscope) I hear chicken. I hear cola fizz, and mustard and relish coagulating together with french fries and onion rings, but you know what? I don't hear a heart.",
  "Carpe Dizem!",
  "man, T at a halfway house man but he'll be 'her",
  "he mafk'n blew himselves up.",
  "I was down with Ray, dawg. Dat old fuckin' white boy...",
  "I'm gonna axe 'em for ya right quick.",
]

ricky = [
  "Lucy is banging cops which is no big deal, I guess. I don't run Lucy. She's for to be her own woman ",
  "Lucy might have a problem, but what Lucy doesn't know won't learn her. ",
  "Get me two bags of chips: Dressed All Over, and Zesty Mordant. ",
  "Yeah, get me some ja-LAP-ano chips ",
  "Worst case Ontario... ",
  "It's basically Peach'n'Cake ",
  "Denial and Error... ",
  "Make my words (Mark)*",
  "Hey Bubs, are you watching that documentary on Saskatchewans?(Sasquatches)*",
  "I'm trying to try here, Sarah.",
  "Who's playing the pianio? ",
  "Make like a tree and fuck off. ",
  "I'm not the kind of person to say atodaso, but you know what? Atodaso, I-fucking-atodaso. ",
  "It was golfing flames, flames just golfing, golfing. ",
  "It's a Catch-23 situation. ",
  "Looks like a tropical earthquake blew through here. ",
  "We can get 2 birds stoned at once. ",
  "Why do you look like Indianapolis Jones? ",
  "He passed with flying fucking carpets. ",
  "It doesn't take rocket appliances. ",
  "Trinity's at the age where it's gorilla see gorilla do. ",
  "Do you got a search warranty for that? (warrant)*",
  "I must be fire retarded or something. ",
  "I'm not a pezmist, I'm an optometrist. ",
  "These plates got me from Tuscany, Arizona to Kentville, Nova Scotia. (Tucson) - Ray, Ricky's Dad",
  "I'll drive you back to the park, Lucy, but there is probably a pretty good chance that it might be over between us ",
  "If my dad and Julian and Bubbles hadn't had been out all night getting lap-dances and getting drunk, the whole thing could have been preventative. ",
  "To be honest with you, I fucking hate bagminten. ",
  "Breaker, Breaker, come in earth. This is Rocketship 27, some aliens fucked over the carbinator in engine number four, we are going to try to refuckulate it and land on Juniper. ",
  "That's not a ladybug. It's a cannerpillar. ",
  "...how to get Buhurbon stains out of Kahayki pants ",
  "One man's garbage is another man person's good ungarbage. ",
  "Au gratin ",
  "I-surance (Insurance)*",
  "Swallow my prize ",
  "Neither here, there, or everywhere ",
  "Boys, let's make toast ",
  "There's no lurches in there, Bubbles, is there? ",
  "I know what you're doing, Lahey, you're trying to fill my feet. ",
  "You gotta remember, every kid goes through phrases. ",
  "What Julian don't grow won't burn him. ",
  "Nice decnals! ",
  "I'm just stretched out! (stressed)*",
  "I don't need your cherry trees. (charity)*",
  "What if he has radies? ",
  "Supply and command. ",
  "What comes around is all around ",
  "What, do you own space? No. Nay-saw does. ",
  "Do unto others as you do unto you. ",
  "One day I will go somewhere that is hot, like Majaica or the Dromedary Republic ",
  "Trinity made a life-ing thing basically out of this chicken. Started with a little eggy thing, and heated it up under these incu-baker things, and it...it was bornt. ",
  "We'll split 50/50/50. ",
  "I hate to have to give you an ultimarium ",
  "It's me or Gumby and Pifuckio ",
  "Raykins! That's what they are, Julian, fuckin' raykins! ",
  "I'm not working for J-Roc, that's against my vice principals ",
  "Bubbles, I don't want any rich peopleman's food, I want some fuckin' meat that's cooked. ",
  "It's survival of the fitness, boys. ",
  "If Randy thinks he's smartener than me, he's wrong. (smarter)*",
  "You gotta do illegal things once in a while, and then maturinate into a better person. ",
  "Your thoughts might be better than mine, but I have thoughts going around in my head too, about...different thinkings...about brain things that you can use and...doing different things.",
  "Sweet empowered chicken things ",
  "It was my mother's mating name. ",
  "Holy shit, you got us a lemon-zine? ",
  "Randy bornt my baby. ",
  "Lucy, I will make you have a eternity test. ",
  "He's gettin' all frustated. ",
  "You can go to college and get your little Pf.D, or whatever the fuck it's called! ",
  "Child reports ",
  "Get us the fuckin' land papers A.S.A.T! ",
  "I'm fucked over from being electromecuted! ",
  "Those them cigarettes in there is our lifes! ",
  "...it's distraculating my case. ",
  "Amernicans! ",
  "I have responsibles now... ",
  "Well, now we gotta go to the library and get a book on horficulture. ",
  "I self-learned myself. ",
  "all right i will. we don’t need to call the cops, i mean, you guys are smarter than real cops. you guys are mall cops! why do we need real cops?",
  "child reports? what? now you got suit dummies makin’ up fancy word papers about me being a bad father because i’m rich now? this is bullshit, lucy!",
  "dad you didn’t know that? i mean, think about it! how would he get around the world in one night? of course he’s the same person.",
  "i can’t get stoned, ricky",
  "i never said doubles, randy. i never said fuckin’ doubles! where’s my chocolate milk and chicken chips?",
  "mostly just family stuff. i mean, well, a man is…is supposed to..always be thinkin’ about stuff about his family and for to make himself to do things that are gonna good-er the family up-around and good-er it up. and that, is what is a man..",
  "ricky, come on, you know santa and god aren’t the same guy, right?",
  "ricky: yeah..us! i’m fuckin stoned right now! you got a problem with that?",
  "sorry…would you welcome me with a little bit of your precious milk, please? is that better??",
  "what do you mean? its shitty work, everybody does that alright? carpenters, electricians, dishwashers, floor cleaners, lawyers, doctors, fuckin’ politicians, cbc employeeds, principals..people who paint the lines on the fuckin’ roads. get stoned, it’ll be fun, get to work.",
  "(eating cereal) actually, sarah, let’s go with the milk,",
  "(to camera) what! yeah, like you guys have never smoked a butt, eh? ohh look at ricky smoking cigarette butts! i’m sick of this shit! i’m sick of your tv show and i’m sick of you and i’m sick of everybody! i’m moving to toronto!",
  "dad, don’t be dissin’ jail. seriously, dont fuckin’ dis jail.",
  "dartmouth regional vocational school….julian, are you fucked in the head?",
  "final warning there, fuckface. final warning.",
  "here’s a little piece of hash, go to the stove, do some hot knives, get stoned, and get to work.",
  "here’s a thousand dollars down, for hook-up fees and six month’s lease up front.",
  "hey, boys! we got a complaint that someone was gettin’ high and drunk and playin’ space in the middle of the street!",
  "he’s gonna give us homemade hot dogs when we’re finished putting the signs up. well i’m gonna give you some homemade fuck-offs right now!",
  "hold on..you do realize that he’s not good at smartly kind of things, he can’t keep a job and he drives like an asshole",
  "hotel security! this man’s drunk as fuck, he’s on drugs, he’s a male prostitute. i’m gonna escort him out of here!",
  "i can’t believe julian bailed me out. i mean, he knows how cool it is in jail at christmas and he ruined it anyways! julians up to something, i fuckin’ know he is!",
  "i can’t get the tree out, it’s stuck! you can’t get the tree out because you’re a nerd! why is there two nerds carrying one tree?! one tree per nerd! god damn fuckin’ nerds.",
  "i just got woken up in the middle of a great dream and i’m pissed off!",
  "i mean, no one wants to admit that they ate 9 cans of ravioli.. but..i did. i’m ashamed of myself.",
  "is that a fuckin’ bone arrow?",
  "i’m not gonna butter-coat this, jacob. what we’re about to do is as dangerous as fuck",
  "i’m sick of looking after everybody. i mean right now, i mean, everyone’s at my dad’s place. fuckin using my car. now he’s borrowing my fucking gun, its bullshit. you know if he thinks he’s better than me, wants to go down and take care of himself, then good cause i don’t want to look after him anymore, and i’ll look after myself. and when he gets back here he’s gonna see who..fucking looks after who…better than…the other person.",
  "look, i don’t need to read people words to understand you or what it means to me, but..something’s fucked up here!",
  "oh you guys have dinners do ya? these are the cheap chicken fingers, you can tell because they have the tiny little crumblies on them!",
  "one man’s garbage is another man’s good ungarbage",
  "ricky, you owe me two double cheeseburgers for cleaning up julian’s trailer!",
  "sparrows are stupid. they don’t give a fuck about anything.",
  "the thing with me is that i am smart and i’m smelf, i’m self smarted, basically, by myself, basically from nature and smoking drugs and doing different things i’ve self…like self learned myself. and that’s the whole difference i guess is that i don’t need the books or the schooling type things. i just get everything on my own and because of that i’m alive right now, because people say books and college are for to make you smarter, but they can also be for to make you dead, which is what could have happened to me. my brain doesn’t use enough oxygen because i don’t have the whole thing filled with different stuff. and if it was full, its only part full and that’s why i’m alive right now.",
  "there’s some illegal procedures going on here! i want this fucking camera crew arrested! i want you arrested for this. i want that sound man arrested. i want everyone arrested!",
  "this is all i got left. i’m telling you right now, i’ll give him some but.. i’m eating half those fajitas. you hear me there steve? or whatever the fuck your name is.",
  "those them cigarettes in there is our lifes",
  "three years’ child support payments you owe, ricky.",
  "to be honest with you, i fuckin’ hate bagminten",
  "trinity has got to quit smoking.. like i can’t have her smoking anymore, it’s ridiculous. she had the idea that maybe me and her can quit together, and its kind of like a good father-daughter thing, so we’re going to quit together. we’re going to go on the patch.",
  "what did you learn about being a man?",
  "what the fuck’s wrong with track pants?",
  "when i was young i did all kinds of crazy shit, and i turned out wicked",
  "who the fuck puts an alarm system in a barn. fuckin’ idiots!",
  "yeah, god. that’s what i said. santa.",
  "you can press charges when the cops get here. they’re on their way.",
  "We got some good dope for 'ya, I'll bring by after work.",
  "I fuckin' warned him about the propane...",
  "Instant karla, fucky!",
  "Jesus christ Jacob, what the fuck was that?",
  "Jesus christ. ",
  "Dope's a part of me, and I cant change that. Dope's a part of everybody. I dont know if you know this, but peoples have this naturally occurring cannabal's sectors in their brain. What the fuck do you think we have those there for? Its for dope to get us high, that's what.",
  "This is all mine now, I have all of this.",
  "Just shutty that fucky!",
  "You look fucked.",
  "Ahhhh hhhhuuuaahhhhhhhhh!",
  "Don't fuckin' shush me.",
  "It fuckin' sucks.",
]

lahey = [
  "When you plant shit-seeds, you get shit-weeds.",
  "Birds of a shitfeather flock together, Randy.",
  "We're in the eye of a shiticane here, Julian, and Ricky's a low-shit system!",
  "Shit-storm troopers",
  "The shit-apple doesn't fall far from the shit-tree",
  "Captain Shittacular",
  "I'm watching you like a shithawk",
  "We're sailing into a shit-typhoon Randy, we'd better haul in the jib before it gets covered in shit.",
  "When you're getting pelted with shitballs, deputy, you gotta get a shit-bat.",
  "The shit pool's gettin full, Randy, time to strain the shit before it overflows. I will not have a Pompeiian catastrophie happening in Sunnyvale.* How dare you involve my daughter in your hemisphere of shit?",
  "Your shit-goose is cooked, Ricky",
  "Shit-apples never fall far from the shit-tree",
  "He's about to enter the shit-tornado to Oz.",
  "Do you know what a shit-rope is Julian? It's a rope covered in shit that criminals try to cling to. Y'see, the shit acts like grease, and the harder you tighten your grip, the more you slide down it.",
  "A shit-leopard can't change its spots.",
  "We need more shit puppets for our play, Randy, and we need angry shit puppets but they aren't mad at us. Shit puppets only get angry at other shit puppets",
  "Randy: Cops and dope don't mix, do they Mr. Lahey? Lahey: Like shit and strawberry shortcake Randy.",
  "I live by the golden rule: if you don't cross my shitline I won't cross yours. But when Ray told everybody in the park that I was drinking again, he crossed the goddamn shitline.",
  "Lahey: Do you know what a shit barometer is, Bubbles? Measures the shit pressure in the air. You can feel it. Listen, Bubs. You hear that? The sounds of the whispering winds of shit? You can hear it.",
  "Do you feel that, Randy, the way the shit clings to the air? Shit Blizzard.",
  "Never Cry Shitwolf.",
  "Did you see that Randy, Goddamn shitapple driving the shitmobile. Nobody else in this park gives a fuck, why should I?",
  "Lahey -You know what's at work here, it's shit tectonics, when two shit plates strike and come together under incredible pressure, do you know what happens, Bubbles?",
  "Yes I used to drink, Randy, but I got the shitmonkey off my back for good.",
  "You just opened Pandora's Shitbox, Ray",
  "You know what you get when two shit-tectonic plates collide? Shitquakes, Julian. Shitquakes.",
  "The ole shit liner is coming to port, and I'll be there to tie her up.",
  "Y'see, Ricky started off as a little shitspark from the ol' shitflint that eventually grew into a shitbonfire, and driven by the winds of his monumental ignorance, grew into a raging shitfirestorm. If I marry Barb, I'll have total control of Sunnyvale, and then I'll be able to unleash a shitnami tidal wave that will extinguish Ricky and his shitflames forever. And with any luck, he'll drown in the undershit of that wave...shitwaves.",
  "Tic Toc, Shit clock's tickin' Rick.",
  "We got the key to shitty city, Ran, and Julian's the muscular mayor.",
  "You boys have loaded up a hair-trigger, double barrelled shitmachinegun, and the barrel's pointing right at your own heads.",
  "Shit flowers, Randy. From a distance they look like ordinary flowers, but when you get right down and stick your nose in them you realize they're shit flowers, and there's a whole fucking bouquet down there right in front of Ray's trailer.",
  "Lahey: Shit moths, Randy. Randy: Is that you or the liquor speaking, Mr Lahey?",
  "Hey Sexian ",
  "Whenever I'm sober, the boys are careful, they're scared of me cause they know what I'll do. They're cautious, it's hard to catch them. But when I'm drinking, their shitguards are down and they fuck up, but the problem is when I'm drinking, I fuck up too, a lot, Barb. I gotta be drinking, but not drinking, ya see? The only way to do that, is to pretend, I am gonna pretend to be drunk, collect evidence and build a solid case against them. Sober as a judge I'm gonna show up today at the cheeseburger picnic, and I'm gonna pretend to be a drunken idiot. And why? Shitguards, Barb...shitguards.",
  "This place is a dump. You have my permission to do whatever you want, any time any place, and you don't have to listen to Pilsbandy Doughboy ",
  "Yeah, well I invited myself. ",
  "But when he shits... he still shits in the park.",
  "Livin' the fuckin dream afghanarandy.",
]

bubbles = [
  "I'd like to see that Red Blue Green cocksucker put one of those together fucking duct taping it.",
  "Dino. Did you call Fred and Barney too? How about Mr. Slate?",
  "I won't tell anyone you have splinters in your lips if you don't tell anyone I have a wooden cock.",
  "Randy: Does that thing really launch, Bubbles? Bubbles: Does the Tin Man have a sheet-metal cock?",
  "Julian, what's a shit hawk? Is it some kind of shitty bird that swoops down and puts poop on you?",
  "Ricky, what happened to your fucking eyes? You look like Alice Cooper?",
  "(in reference to the Helix song Rock You) I'm not giving anyone a fucking R!",
  "Ricky, those laws are there to protect kids, not so goofballs like you can put them in the car with no door on it, and drive around the fuckin' neighbourhood stealin' barbecues!",
  "Can I come out now? I think I have a leech on my bird.",
  "Julian, we're both baked. That's why were probably not making any sense.",
  "No, he's just a really big kitty, and he's baked!",
  "Bubbles: Stealing gas? Why, Cory and Trevor, that's highly illegal, you shouldn't be stealing gas, Cory and Trevor.",
  "(Rapping) I got a grey kitty, white one, and a tabby too/ And a big orange guy who put snakes in my shoes/ Mad MC skills, leave ya struck, and I roll with ma kitties, and I'am hard as fuck/ I am down with Plato and Socrates/ And I like to get busy with all the ladies. Grunt, grunt/ sumthin,' sumthin,' sumthin,'/ Grunt/ Up in ma shed, up in ma shed...",
  "Holy fuck boys, this shed is like a fucking palace! Indoor plumbing (toilet seat inside), satellite tv, 400 channels, anything I wanna watch, it's right there, space for my kitties, Mobile phone, new technology (holds up an ancient mobile phone), this is the best fucking shed there ever was!",
  "Here, Cory-Trevor, Cory-Trevor!",
  "Hampton: Can you read, my son? Bubbles: Well, that depends, can you go fuck yourself?",
  "Trevor: Julian, this looks like a pirate gun. Bubbles: Well Trevor, I guess that makes you Long John Dickweed, then.",
  "Green Bastard, from parts unknown (grunts and inhales).",
  "Lahey, can you please get the flyin' fuck out of our way!",
  "COCK-SUCKER!",
  "There's a note pinned to a tree! Diddly-dee!",
  "(To Randy re: cheeseburgers) How many did you drive into that big fuckin cheeseburger-locker?",
  "Well, when I was a little guy, I always wanted to go up into space, be a space-man. But you gotta be able to see really fuckin' good to do that job. Some guy would take one look at me and say 'Uhhh, sorry sir, you gotta be able to see a little better than you'... I don't give a fuck.",
  "Holy sweet flying fuck!",
  "(grunts)",
  "(whimpering)",
  "Cocksucker!",
  "Son of a whore! ",
  "Hey boys, how's she goin'?",
  "The government. Harrrrd cock to suck.",
  "This could be a fuckin' life changer. This could be a mansion!",
]

julian = [
  "Fuck's sakes."
]

ray = [
  "Fucking way she goes.",
]

module.exports = (robot) ->
  robot.hear /(?!:)(bubbles)(?!:)/i, (msg) ->
    msg.send ":bubbles:: \n>" + msg.random bubbles

  robot.hear /(?!:)(ricky|rickey)(?!:)/i, (msg) ->
    msg.send ":ricky:: \n>" + msg.random ricky

  robot.hear /(?!:)(j-roc|jroc|j roc)(?!:)/i, (msg) ->
    msg.send ":jroc:: \n>" + msg.random jroc

  robot.hear /(?!:)(lahey)(?!:)/i, (msg) ->
    msg.send ":lahey:: \n>" + msg.random lahey

  robot.hear /(?!:)(julian)(?!:)/i, (msg) ->
    msg.send ":julian:: \n>" + msg.random julian

  robot.hear /(?!:)(ray)(?!:)/i, (msg) ->
    msg.send ":ray:: \n>" + msg.random ray
